logging:
  level:
    root: "info"

management:
  endpoints:
    web:
      # base-path: "/" # default value is "/actuator"
      exposure:
        include: "*"

zuul:
  routes:
    test:
      path: "/test/**"
      url: "https://www.google.com"
